# Generated by Django 4.2.13 on 2024-07-14 20:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blogg', '0002_new_delete_new_post'),
    ]

    operations = [
        migrations.AlterField(
            model_name='new',
            name='status',
            field=models.CharField(choices=[('pub', 'publishded successfully'), ('dra', 'saved as draft')], max_length=3),
        ),
    ]
